# Generated by Django 5.0.14 on 2026-07-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='has_unreflected_review',
        ),
        migrations.RemoveField(
            model_name='task',
            name='last_review_added_at',
        ),
        migrations.AddField(
            model_name='task',
            name='checklist_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='체크리스트 마지막 생성 일시'),
        ),
    ]
